#!/usr/bin/bash

dir="$HOME/.config/rofi/power.rasi"

shutdown=" Shutdown"
reboot="󰜉 Reboot"
suspend="⏾ Suspend"
lock="󰌾 Lock"
logout="󰍃 Logout"

options="$shutdown\n$reboot\n$suspend\n$lock\n$logout"

choice=$(echo -e "$options" | rofi -dmenu -theme "$dir" -no-custom -lines 5)
case "$choice" in
    "$shutdown")
        systemctl poweroff
        ;;
    "$reboot")
        systemctl reboot
        ;;
    "$suspend")
        systemctl suspend
        ;;
    "$lock")
        # TODO: add lock behavior, betterlockscreen?
        ;;
    "$logout")
        if pgrep -x "hyprland" > /dev/null; then
            hyprctl dispatch exit
        elif pgrep -x "niri" > /dev/null; then
            niri msg action quit
        fi
        ;;
esac
