#!/usr/bin/bash

dir="$HOME/.config/rofi/power.rasi"

shutdown="Shutdown"
shutdown_icon="\0icon\x1fsystem-shutdown"

reboot="Reboot"
reboot_icon="\0icon\x1fsystem-restart"

suspend="Suspend"
suspend_icon="\0icon\x1fsystem-suspend"

lock="Lock"
lock_icon="\0icon\x1flock"

logout="Logout"
logout_icon="\0icon\x1fsystem-log-out"

options="$shutdown$shutdown_icon\n$reboot$reboot_icon\n$suspend$suspend_icon\n$lock$lock_icon\n$logout$logout_icon"

# Must have ~/.icons/dracula-icons
# See https://github.com/m4thewz/dracula-icons
choice=$(echo -e "$options" | rofi -dmenu -theme "$dir" -no-custom -icon-theme dracula-icons)
case "$choice" in
    "$shutdown")
        systemctl poweroff
        ;;
    "$reboot")
        systemctl reboot
        ;;
    "$suspend")
        systemctl suspend
        ;;
    "$lock")
        # TODO: add lock behavior, betterlockscreen?
        ;;
    "$logout")
        if pgrep -x "hyprland" > /dev/null; then
            hyprctl dispatch exit
        elif pgrep -x "niri" > /dev/null; then
            niri msg action quit --skip-confirmation
        fi
        ;;
esac
