#!/usr/bin/env bash

# Until SwayOSD decides to let user's specify LED class name for brightnessctl, I have to use this
# script to change keyboard brightness and show an OSD
# See https://github.com/ErikReider/SwayOSD/issues/35

# Check if exactly one argument is passed
if [ $# -ne 1 ]; then
    echo "Usage: $0 [raise|lower]"
    exit 1
fi

case "$1" in
    raise)
        brightnessctl -d asus::kbd_backlight set 20%+
        ;;
    lower)
        brightnessctl -d asus::kbd_backlight set 20%-
        ;;
    *)
        echo "Invalid argument: $1"
        echo "Usage: $0 [raise|lower]"
        exit 1
        ;;
esac

brightness=$(brightnessctl -d asus::kbd_backlight get)
percent=$(echo "scale=2; $brightness / 3" | bc)  # Need to use command for decimal arithmetic

# For some reason passing 0 doesn't actually work
if [ "$percent" = "0" ]; then
    percent="0.00000000000001"
fi

swayosd-client --custom-progress="$percent"
