#!/usr/bin/env bash

network="Network"
network_icon="\0icon\x1fnetwork-wireless"

bluetooth="Bluetooth"
bluetooth_icon="\0icon\x1fnetwork-bluetooth"

alarm="Alarms"
alarm_icon="\0icon\x1falarm-symbolic"

options="$network$network_icon\n$bluetooth$bluetooth_icon\n$alarm$alarm_icon"

# Must have ~/.icons/dracula-icons
# See https://github.com/m4thewz/dracula-icons
choice=$(echo -e "$options" | fuzzel --dmenu --font=":size=16")
case "$choice" in
    "$network")
        ~/.local/bin/iwmenu --launcher fuzzel
        ;;
    "$bluetooth")
        ~/.local/bin/bzmenu --launcher fuzzel
        ;;
    "$alarm")
        ~/.config/niri/alarm
        ;;
esac
