#!/usr/bin/python

import os
from socket import AF_UNIX, socket
import subprocess
import sys
import time
import json
from typing import TypedDict, cast

WINDOW_CLASS = "dvt_screensaver"


class Layout(TypedDict):
    pos_in_scrolling_layout: list[int]
    tile_size: list[int]
    window_size: list[int]
    tile_pos_in_workspace_view: bool | None
    window_offset_in_tile: list[int]


class FocusedWindowResp(TypedDict):
    id: int
    title: str
    app_id: str
    pid: int
    workspace_id: int
    is_focused: bool
    is_floating: bool
    is_urgent: bool
    layout: Layout


class OkResp(TypedDict):
    FocusedWindow: FocusedWindowResp | None


class NiriReply(TypedDict, total=False):
    Ok: OkResp
    Err: str


def run_screensaver() -> bool:
    font_size = 22
    EXCLUDED = "print colorshift highlight scattered"
    inner_cmd = f"""
            while true; do
                # Clear screen before each effect for a fresh start
                clear
                fortune -a | tte \
                        --anchor-canvas c --anchor-text c --canvas-width 0 --canvas-height 0 \
                        --random-effect \
                        --exclude-effects {EXCLUDED} \
                        --no-eol \
                        --no-restore-cursor \
                        --frame-rate 120 \
                        --terminal-background-color 282A36
                sleep 5
            done
            """
    _ = subprocess.Popen(
        [
            "wezterm-gui",
            "--config",
            f"font_size={font_size}",
            "start",
            "--class",
            WINDOW_CLASS,
            "--",
            "sh",
            "-c",
            f"sleep 0.4 && {inner_cmd}",
        ]
    )

    time.sleep(0.6)

    if not screensaver_is_open():
        print("Something went wrong opening the screensaver", file=sys.stderr)
        return False

    _ = subprocess.Popen(["niri", "msg", "action", "fullscreen-window"]).wait()
    return True


def screensaver_is_open() -> bool:
    # See https://yalter.github.io/niri/niri_ipc/index.html
    sock = socket(AF_UNIX)
    sock.connect(os.environ["NIRI_SOCKET"])
    sock.send(b'"FocusedWindow"\n')
    chunk = sock.recv(4096)
    sock.close()
    niri_reply = cast(NiriReply, json.loads(chunk))

    if "Err" in niri_reply:
        print("Error communicating with Niri:", niri_reply["Err"], file=sys.stderr)
        exit(1)
    assert "Ok" in niri_reply

    focused_window = niri_reply["Ok"]["FocusedWindow"]
    if focused_window is None:  # No window is currently open in the current workspace
        return False

    app_id = focused_window["app_id"].strip()
    return app_id == WINDOW_CLASS


def run():
    if screensaver_is_open():
        print("A screensaver is already running!")
        exit(1)

    run_screensaver()


def close():
    if not screensaver_is_open():
        print("Attempted to close a screensaver but none is open!")
        exit(0)

    output = subprocess.run(
        ["niri", "msg", "action", "close-window"], capture_output=True
    )
    if output.returncode != 0:
        print(
            "Something went wrong closing the screensaver",
            output.stderr,
            file=sys.stderr,
        )
        exit(output.returncode)
    print("Closed screensaver!")


ARGS = {"run": run, "close": close}

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Must specify one argument, either 'run' or 'close'")
        exit(1)

    action = sys.argv[1]
    action_is_valid = action in ARGS.keys()
    if not action_is_valid:
        print(f"{action} is not valid argument, either 'run' or 'close'")
        exit(1)

    ARGS[action]()
