# Config relating to the Lazygit UI
gui:
  # One of 'auto' (default) | 'en' | 'zh-CN' | 'zh-TW' | 'pl' | 'nl' | 'ja' | 'ko' | 'ru'
  language: en

  # Format used when displaying time e.g. commit time.
  # Uses Go's time format syntax: https://pkg.go.dev/time#Time.Format
  timeFormat: 02 January 2006

  # Format used when displaying time if the time is less than 24 hours ago.
  # Uses Go's time format syntax: https://pkg.go.dev/time#Time.Format
  shortTimeFormat: 15:04

  # Nerd fonts version to use.
  # One of: '2' | '3' | empty string (default)
  # If empty, do not show icons.
  nerdFontsVersion: "3"

  # If true (default), file icons are shown in the file views. Only relevant if NerdFontsVersion is not empty.
  showFileIcons: true

  # Config relating to the spinner.
  spinner:
    # The frames of the spinner animation.
    frames:
      - '⠋'
      - '⠙'
      - '⠹'
      - '⠸'
      - '⠼'
      - '⠴'
      - '⠦'
      - '⠧'
      - '⠇'
      - '⠏'

    # The "speed" of the spinner in milliseconds.
    rate: 50

# Config relating to git
git:
  # If true, parse emoji strings in commit messages e.g. render :rocket: as 🚀
  # (This should really be under 'gui', not 'git')
  parseEmoji: true

# If true, don't display introductory popups upon opening Lazygit.
disableStartupPopups: true

# If true, do not allow force pushes
disableForcePushing: true
