[mgr]
show_hidden = true
linemode = "size_and_mtime"
scrolloff = 10

[opener]
edit = [
    { run = 'nvim "$@"', block = true }
]

[preview]
max_width=1920
max_height=1440

[plugin]
prepend_previewers = [
    { mime = "{image,audio,video}/*", run = "mediainfo" },
    { mime = "application/x-subrip", run = "mediainfo" },
    { mime = "text/csv", run = "miller" },
    { name = "*.md", run = "glow" },
]

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
